version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/demo.thebitcoinfreedom.com
    steps:
      - checkout
      - add_ssh_keys
      - run:
          command: echo '144.76.199.215 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNQmCt85vFWpSVWrW2qcnLKigC3LhCWRwTiZcGLriQCB/0H9qoKdmG3OM/Bn7Lr8yAWIJjEsok4fViRKd8hTcBA=' >> ~/.ssh/known_hosts
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm update
          command: npm update
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: CI="false" npm run build
      - run:
          name: deploy via scp
          command: |
            scp -r ~/demo.thebitcoinfreedom.com/build/* admin@144.76.199.215:~/web/demo.thebitcoinfreedom.com/public_html
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build-and-deploy:
    jobs:
      - cypress/run:
          executor: cypress/base-8
          start: npm start
          wait-on: 'http://localhost:3000'
      - build:
          filters:
            branches:
              only: cypress
